name: Run Colab Notebook

on:
  workflow_dispatch:   # 수동 실행 가능
  schedule:
    - cron: '0 * * * *'  # 매일 오전 9시 실행

jobs:
  run_colab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Execute Colab Notebook
        run: |
          python run_colab.py
