name: Run Jupyter Notebook

# 수동 실행 및 스케줄 가능
on:
  workflow_dispatch:
  schedule:
    - cron: '7 * * * *'  # 매일 오전 9시 실행

jobs:
  execute_notebook:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Python 환경 설정
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. 필요한 라이브러리 설치
      - name: Install dependencies
        run: |
          pip install jupyter nbconvert pandas numpy matplotlib

      # 4. 노트북 실행
      - name: Execute Notebook
        run: |
          jupyter nbconvert --to notebook --execute runStock.ipynb --output executed_notebook.ipynb
