name: Test GitHub Action Demo-01
run-name: Run GitHub Actions-01 🚀
on: [push]

jobs:
  Test-GitHub-Action:
    runs-on: ubuntu-latest
    steps:
      - name: echo-01
        run: |
          echo "TEST ECHO-01"
